openapi: "3.0.0"
info:
  title: 'API Gateway & Function Compute'
  version: v1
components:
  securitySchemes:
    openId:
      type: openIdConnect
      name: 'token'
      in: 'query'
'/wechat':
  get:
    x-aliyun-apigateway-parameters:
      - name: 'encrypt_type'
      - name: 'msg_signature'
      - name: 'timestamp'
        location: 'Query'
        type: 'String'
        required: 'REQUIRED'
      - name: 'nonce'
        location: 'Query'
        type: 'String'
      - name: 'signature'
        location: 'Query'
        type: 'String'
      - name: 'echostr'
        location: 'Query'
        type: 'String'
    x-aliyun-apigateway-fc:
      arn: acs:fc:::services/${wechat.Arn}/functions/${get.Arn}/
      role: acs:ram:::role/aliyunapigatewayaccessingfcrole
  post:
    requestBody:
      content:
        application/octet-stream: 
          schema:
            type: string
            format: binary
    x-aliyun-apigateway-parameters:
      - name: 'timestamp'
        location: 'Query'
        type: 'String'
        required: 'REQUIRED'
      - name: 'nonce'
        location: 'Query'
        type: 'String'
      - name: 'signature'
        location: 'Query'
        type: 'String'
      - name: 'msg_signature'
        location: 'Query'
        type: 'String'
      - name: 'encrypt_type'
        location: 'Query'
        type: 'String'
    x-aliyun-apigateway-fc:
      arn: acs:fc:::services/${wechat.Arn}/functions/${post.Arn}/
      role: acs:ram:::role/aliyunapigatewayaccessingfcrole